#:schema node_modules/wrangler/config-schema.json
name = "palma-worker"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
SLACK_CHANNEL_ID = "C12345678"

[[kv_namespaces]]
binding = "PALMA_HAYEK_KV"
id = "27b837c04dc14a5fb56c732cd2673283"
